version: '3.6'

services:
  postgres:
    ports:
      - "5432:5432"

  graphql_engine:
    ports:
      - "8080:8080"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata